baseURL: https://afk.best/
languageCode: en-us
title: Afkortingen
googleAnalytics: UA-19569086-7
enableRobotsTXT: true
disableKinds:
    - taxonomy
    - taxonomyTerm
    - RSS

# Language settings
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
    en:
        weight: 1
        languageName: English
    ru:
        weight: 2
        languageName: Русский
        params:
            author: Дмитрий Канн
            description: 'Распространённые сокращения нидерландского языка и их перевод на русский'
            keywords:
                - сокращение
                - нидерландский язык
                - голландский язык
                - Нидерланды
                - Голландия
                - перевод

# Params
params:
    author: Dmitry Kann
    description: 'Common Dutch abbreviations and their translations into English'
    keywords:
        - abbreviation
        - Dutch language
        - Netherlands
        - Holland
        - translation
